site_name: Luau FFT Documentation
site_url: https://tenx29.github.io/Luau-FFT/
repo_name: tenx29/Luau-FFT
repo_url: https://github.com/tenx29/Luau-FFT/

nav:
  - About: index.md
  - API Reference:
    - Complex Mathematics: api-reference/cmath.md
    - Fourier: api-reference/fourier.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: 'slate'
    primary: 'blue'
    accent: 'light blue'
    

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 TenX29
